const productsList = [
  {
    id_product: 1,
    category: "nacional",
    fk_idcategory: 1,
    name_product: "Flamengo 2020",
    price: 300,
    image: "./images/produtos/fla.jpg",
    id_category: 1,
    name_category: "Clubes brasileiros",
    selected: false,
  },
  {
    id_product: 2,
    category: "nacional",
    fk_idcategory: 1,
    name_product: "Palmeiras 2020",
    price: 350,
    image: "./images/produtos/palmeiras.jpg",
    id_category: 1,
    name_category: "Clubes brasileiros",
    selected: false,
  },
  {
    id_product: 9,
    category: "nacional",
    fk_idcategory: 1,
    name_product: "Grêmio 2020",
    price: 230,
    image: "./images/produtos/gremio.jpg",
    id_category: 1,
    name_category: "Clubes brasileiros",
    selected: false,
  },
  {
    id_product: 4,
    category: "europeu",
    fk_idcategory: 2,
    name_product: "Arsenal 2020/2021",
    price: 399.99,
    image: "./images/produtos/arsenal.jpg",
    id_category: 2,
    name_category: "Clubes europeus",
    selected: false,
  },
  {
    id_product: 10,
    category: "europeu",
    fk_idcategory: 2,
    name_product: "Manchester City 2020/2021",
    price: 399.99,
    image: "./images/produtos/man-city.jpg",
    id_category: 2,
    name_category: "Clubes europeus",
    selected: false,
  },
];

export default productsList;
